# Data-X Spring 2019: Homework 06 

## Name : Wesley Chen
## SID : 3031961388
## Course (IEOR 135/290) : IEOR 135

### Machine Learning



In this homework, you will do some exercises with prediction. We will cover these algorithms in class, but this is for you to have some hands on with these in scikit-learn. You can refer - https://github.com/ikhlaqsidhu/data-x/blob/master/05a-tools-predicition-titanic/titanic.ipynb

Display all your outputs.


In [193]:
import numpy as np
import pandas as pd

In [194]:
 # machine learning libraries
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.linear_model import Perceptron
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split



__ 1. Read __`diabetesdata.csv`__ file into a pandas dataframe. 
About the data: __

1. __TimesPregnant__: Number of times pregnant 
2. __glucoseLevel__: Plasma glucose concentration a 2 hours in an oral glucose tolerance test 
3. __BP__: Diastolic blood pressure (mm Hg)  
5. __insulin__: 2-Hour serum insulin (mu U/ml) 
6. __BMI__: Body mass index (weight in kg/(height in m)^2) 
7. __pedigree__: Diabetes pedigree function 
8. __Age__: Age (years) 
9. __IsDiabetic__: 0 if not diabetic or 1 if diabetic) 








In [195]:
#Read data & print the head
data = pd.DataFrame(pd.read_csv('diabetesdata.csv'))
data.head()


TimesPregnant  glucoseLevel  BP  insulin   BMI  Pedigree   Age  IsDiabetic
0              6         148.0  72        0  33.6     0.627  50.0           1
1              1           NaN  66        0  26.6     0.351  31.0           0
2              8         183.0  64        0  23.3     0.672   NaN           1
3              1           NaN  66       94  28.1     0.167  21.0           0
4              0         137.0  40      168  43.1     2.288  33.0           1

**2. Calculate the percentage of Null values in each column and display it. **

In [196]:
for i in range(8):
    print(sum(data.iloc[:,i].isna())/ len(data.iloc[:,i]))

0.0
0.044270833333333336
0.0
0.0
0.0
0.0
0.04296875
0.0


**3. Split __`data`__  into  __`train_df`__ and __`test_df`__  with 15% as test.**


In [197]:
train_df, test_df  = train_test_split(data, test_size=0.15, shuffle = True)

**4. Display the means of the features in train and test sets. Replace the null values in  __`train_df`__ and __`test_df`__  with the mean of EACH feature column separately for train and test. Display head of the dataframes.**

In [198]:
train_glucose_mean = train_df['glucoseLevel'].mean()
train_age_mean = train_df['Age'].mean()

test_glucose_mean = test_df['glucoseLevel'].mean()
test_age_mean = test_df['Age'].mean()

train_df['glucoseLevel'].fillna(train_glucose_mean, inplace = True)
train_df['Age'].fillna(train_age_mean, inplace = True)

test_df['glucoseLevel'].fillna(test_glucose_mean, inplace = True)
test_df['Age'].fillna(test_age_mean, inplace = True)

display(train_df.head())
display(test_df.head())

/Users/wesleychen/anaconda3/envs/data-x/lib/python3.6/site-packages/pandas/core/generic.py:5434: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


TimesPregnant  glucoseLevel  BP  insulin   BMI  Pedigree   Age  \
683              4         125.0  80        0  32.3     0.536  27.0   
360              5         189.0  64      325  31.2     0.583  29.0   
427              1         181.0  64      180  34.1     0.328  38.0   
350              4          92.0  80        0  42.2     0.237  29.0   
567              6          92.0  62      126  32.0     0.085  46.0   

     IsDiabetic  
683           1  
360           1  
427           1  
350           0  
567           0

TimesPregnant  glucoseLevel  BP  insulin   BMI  Pedigree   Age  \
558             11         103.0  68        0  46.2     0.126  42.0   
173              1          79.0  60       48  43.5     0.678  23.0   
628              5         128.0  80        0  34.6     0.144  45.0   
465              0         124.0  56      105  21.8     0.452  21.0   
346              1         139.0  46       83  28.7     0.654  22.0   

     IsDiabetic  
558           0  
173           0  
628           0  
465           0  
346           0

**5. Split __`train_df`__ & __`test_df`__   into  __`X_train`__, __`Y_train`__  and __`X_test`__, __`Y_test`__. __`Y_train`__  and __`Y_test`__ should only have the column we are trying to predict,  __`IsDiabetic`__.**

In [199]:
x_train = train_df.drop('IsDiabetic', axis =1)
y_train = train_df['IsDiabetic']
x_test = test_df.drop('IsDiabetic', axis =1)
y_test = test_df['IsDiabetic']

display(x_train.head(), y_train.head(), x_test.head(), y_test.head())

TimesPregnant  glucoseLevel  BP  insulin   BMI  Pedigree   Age
683              4         125.0  80        0  32.3     0.536  27.0
360              5         189.0  64      325  31.2     0.583  29.0
427              1         181.0  64      180  34.1     0.328  38.0
350              4          92.0  80        0  42.2     0.237  29.0
567              6          92.0  62      126  32.0     0.085  46.0

683    1
360    1
427    1
350    0
567    0
Name: IsDiabetic, dtype: int64

TimesPregnant  glucoseLevel  BP  insulin   BMI  Pedigree   Age
558             11         103.0  68        0  46.2     0.126  42.0
173              1          79.0  60       48  43.5     0.678  23.0
628              5         128.0  80        0  34.6     0.144  45.0
465              0         124.0  56      105  21.8     0.452  21.0
346              1         139.0  46       83  28.7     0.654  22.0

558    0
173    0
628    0
465    0
346    0
Name: IsDiabetic, dtype: int64

**6. Use this dataset to train perceptron, logistic regression and random forest models using 15% test split. Report training and test accuracies. Try different hyperparameter values for these models and see if you can improve your accuracies.**

In [246]:
# 6a. Logistic Regression

logreg = LogisticRegression()
logreg.fit(x_train, y_train)
train_acc_logreg = logreg.score(x_train, y_train)
test_acc_logreg = logreg.score(x_test,y_test)

print('Logistic Regression training accuracy:', str(round(train_acc_logreg*100,2)),'%')
print('Logistic Regression testing accuracy:', str(round(test_acc_logreg*100,2)),'%')

a_logreg = LogisticRegression(C = 10)
a_logreg.fit(x_train, y_train)
a_train_acc_logreg = a_logreg.score(x_train, y_train)
a_test_acc_logreg = a_logreg.score(x_test,y_test)

print('C = 10 Logistic Regression training accuracy:', str(round(a_train_acc_logreg*100,2)),'%')
print('C = 10 Logistic Regression testing accuracy:', str(round(a_test_acc_logreg*100,2)),'%')

b_logreg = LogisticRegression(C = 8)
b_logreg.fit(x_train, y_train)
b_train_acc_logreg = b_logreg.score(x_train, y_train)
b_test_acc_logreg = b_logreg.score(x_test,y_test)

print('C = 8 Logistic Regression training accuracy:', str(round(b_train_acc_logreg*100,2)),'%')
print('C = 8 Logistic Regression testing accuracy:', str(round(b_test_acc_logreg*100,2)),'%')

Logistic Regression training accuracy: 77.15 %
Logistic Regression testing accuracy: 81.9 %
C = 10 Logistic Regression training accuracy: 77.61 %
C = 10 Logistic Regression testing accuracy: 81.03 %
C = 8 Logistic Regression training accuracy: 77.76 %
C = 8 Logistic Regression testing accuracy: 81.03 %


/Users/wesleychen/anaconda3/envs/data-x/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/wesleychen/anaconda3/envs/data-x/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/wesleychen/anaconda3/envs/data-x/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [230]:
# 6b. Perceptron
perceptron = Perceptron()
perceptron.fit(x_train, y_train)
train_acc_perceptron = perceptron.score(x_train, y_train)
test_acc_perceptron = perceptron.score(x_test, y_test)

print('Perceptron training accuracy:', str(round(train_acc_perceptron*100,2)),'%')
print('Perceptron testing accuracy:', str(round(test_acc_perceptron*100,2)),'%')

a_perceptron = Perceptron(tol = 0.01)
a_perceptron.fit(x_train, y_train)
a_train_acc_perceptron = a_perceptron.score(x_train, y_train)
a_test_acc_perceptron = a_perceptron.score(x_test, y_test)

print('tol = 0.01 Perceptron training accuracy:', str(round(a_train_acc_perceptron*100,2)),'%')
print('tol = 0.01 Perceptron testing accuracy:', str(round(a_test_acc_perceptron*100,2)),'%')

b_perceptron = Perceptron(max_iter = 0.1)
b_perceptron.fit(x_train, y_train)
b_train_acc_perceptron = b_perceptron.score(x_train, y_train)
b_test_acc_perceptron = b_perceptron.score(x_test, y_test)

print('Max_iter = 0.1 Perceptron training accuracy:', str(round(b_train_acc_perceptron*100,2)),'%')
print('Max_iter = 0.1 Perceptron testing accuracy:', str(round(b_test_acc_perceptron*100,2)),'%')

Perceptron training accuracy: 63.5 %
Perceptron testing accuracy: 75.0 %
tol = 0.01 Perceptron training accuracy: 64.88 %
tol = 0.01 Perceptron testing accuracy: 74.14 %
Max_iter = 0.1 Perceptron training accuracy: 63.8 %
Max_iter = 0.1 Perceptron testing accuracy: 72.41 %


/Users/wesleychen/anaconda3/envs/data-x/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)
/Users/wesleychen/anaconda3/envs/data-x/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


In [203]:
# 6c. Random Forest

random_forest = RandomForestClassifier(n_estimators=500)
random_forest.fit(x_train, y_train)
train_acc_rf = random_forest.score(x_train, y_train)
test_acc_rf = random_forest.score(x_test, y_test)

print('K-Nearest Neighbors training accuracy:', str(round(train_acc_rf*100,2)),'%')
print('K-Nearest Neighbors testing accuracy:', str(round(test_acc_rf*100,2)),'%')

a_random_forest = RandomForestClassifier(n_estimators=100)
a_random_forest.fit(x_train, y_train)
a_train_acc_rf = a_random_forest.score(x_train, y_train)
a_test_acc_rf = a_random_forest.score(x_test, y_test)

print('n_estimators = 100 K-Nearest Neighbors training accuracy:', str(round(a_train_acc_rf*100,2)),'%')
print('n_estimators = 100 K-Nearest Neighbors testing accuracy:', str(round(a_test_acc_rf*100,2)),'%')

b_random_forest = RandomForestClassifier(n_estimators=500, bootstrap = False)
b_random_forest.fit(x_train, y_train)
b_train_acc_rf = b_random_forest.score(x_train, y_train)
b_test_acc_rf = b_random_forest.score(x_test, y_test)

print('bootstrap = False K-Nearest Neighbors training accuracy:', str(round(b_train_acc_rf*100,2)),'%')
print('bootstrap = False K-Nearest Neighbors testing accuracy:', str(round(b_test_acc_rf*100,2)),'%')

K-Nearest Neighbors training accuracy: 100.0 %
K-Nearest Neighbors testing accuracy: 77.59 %
n_estimators = 100 K-Nearest Neighbors training accuracy: 100.0 %
n_estimators = 100 K-Nearest Neighbors testing accuracy: 79.31 %
bootstrap = False K-Nearest Neighbors training accuracy: 100.0 %
bootstrap = False K-Nearest Neighbors testing accuracy: 79.31 %


**7. For your logistic regression model - **

**a . Compute the log probability of classes in  __`IsDiabetic`__ for the first 10 samples of your train set and display it. Also display the predicted class for those samples from your logistic regression model trained before. **


In [260]:
display(logreg.predict_log_proba(train_df.iloc[:10,:7]))
display(logreg.predict(train_df.iloc[:10,:7]))

array([[-0.42139495, -1.06749426],
       [-1.40807299, -0.28052667],
       [-1.06434592, -0.42304891],
       [-0.27971233, -1.41059192],
       [-0.23981822, -1.54538794],
       [-0.46134733, -0.99542505],
       [-0.19647614, -1.72384443],
       [-2.02303877, -0.14185504],
       [-1.79148978, -0.1823755 ],
       [-0.9262286 , -0.50425483]])

array([0, 1, 1, 0, 0, 0, 0, 1, 1, 1])

**b . Now compute the log probability of classes in  __`IsDiabetic`__ for the first 10 samples of your test set and display it. Also display the predicted class for those samples from your logistic regression model trained before.
 (using the model trained on the training set)**


In [261]:
display(logreg.predict_log_proba(test_df.iloc[:10,:7]))
display(logreg.predict(test_df.iloc[:10,:7]))

array([[-0.90184896, -0.52057066],
       [-0.26347628, -1.46263927],
       [-0.48872079, -0.95039207],
       [-0.19294558, -1.74026921],
       [-0.54756412, -0.86359606],
       [-0.84166228, -0.56386342],
       [-0.17459089, -1.83133552],
       [-1.84491502, -0.17202129],
       [-0.06659541, -2.74223254],
       [-0.07295434, -2.65417698]])

array([1, 0, 0, 0, 0, 1, 0, 1, 0, 0])

**c . What can you interpret from the log probabilities and the predicted classes?**



Log probabilities gives the log of the probability that the predicted class is either 1 or 0. 

**8. Is mean imputation is the best type of imputation (as we did in 4.) to use? Why or why not? What are some other ways to impute the data?**

Mean is not the best type of imputation because outliers can affect it. Median might be a better way to impute the data because outliers won't affect it and it might maintain the same whole number inputs as the other inputs whereas the mean would most likely not. 

## Extra Credit (2 pts) - MANDATORY for students enrolled in IEOR 290


**9.  Implement the K-Nearest Neighbours (https://en.wikipedia.org/wiki/K-nearest_neighbors_algorithm) algorithm for k=1 from scratch in python (do not use KNN from existing libraries). KNN uses Euclidean distance to find nearest neighbors. Split your dataset into test and train as before. Also fill in the null values with mean of features as done earlier. Use this algorithm to predict values for 'IsDiabetic' for your test set. Display your accuracy. **